// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Color } from "./Color";
import type { Icon } from "./Icon";
import type { Image } from "./Image";
import type { Item } from "./Item";
import type { Title } from "./Title";

export type ActionDto = { item: Item, title: Title | null, image: Image | null, icon: Icon | null, color: Color | null, };
