// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionDto } from "./ActionDto";
import type { Board } from "./Board";
import type { Page } from "./Page";

export type BoardDto = { board: Board, page: Page | null, actions: Array<ActionDto>, };
