// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateItem = { id: number | null, boardId: number, row: number, col: number, kind: string, };
