// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateColor } from "./CreateColor";
import type { CreateIcon } from "./CreateIcon";
import type { CreateImage } from "./CreateImage";
import type { CreateItem } from "./CreateItem";
import type { CreateTitle } from "./CreateTitle";

export type CreateActionDto = { item: CreateItem, title: CreateTitle | null, image: CreateImage | null, icon: CreateIcon | null, color: CreateColor | null, };
