// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateBoard } from "./CreateBoard";

export type CreateBoardDto = { board: CreateBoard, };
