// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateTitle = { itemId: number | null, value: string | null, align: string | null, color: string | null, size: number | null, font: string | null, };
