// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateImage = { itemId: number | null, file: string | null, imageType: string | null, };
