// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Page = { boardId: number, position: number, name: string | null, icon: string | null, };
