// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Style = { profileId: number, spacing: number | null, borderRadius: number | null, backgroundImage: string | null, backgroundColor: string | null, };
